### ISSUE TITLE
cant get in ui 

### ISSUE THREAD

**Issue by oly99** [otkd/balena-myst#6]
hi do you know any issues with getting into the ui and how to fix them im getting error myst  2024-02-28T23:38:02.518 WRN ../../ui/server.go:94                          > could not read node ui version config, falling back to bundled version
 myst  2024-02-28T23:38:02.519 DBG ../../config/config.go:216                     > Returning CLI value local-service-discovery:false

**Comment by otkd** [comment]
Not that I'm aware of
